version: "3.9"

services:
  pytorch:
    image: pytorch/pytorch:2.9.1-cuda12.6-cudnn9-runtime
    container_name: pytroch-gpu
    command: "/bin/bash"
    privileged: true
    tty: true
    stdin_open: true
    gpus: "all"
